repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/adrienverge/yamllint.git
    rev: 'v1.23.0'
    hooks:
      - id: yamllint
        name: Check for Linting error on YAML files
        description: This hook runs yamllint.
        entry: yamllint
        language: python
        types: [file, yaml]
        args: [-c=.yamllint]
